name = "casflo-worker-api"
main = "src/index.ts"
compatibility_date = "2025-11-25"
type = "javascript"

[[d1_databases]]
binding = "DB"
database_name = "CASFLO_DB"

[vars]
ACCESS_TOKEN_EXPIRES = "15m"
REFRESH_TOKEN_EXPIRES_DAYS = "30"
