name = "casflo-api"
main = "src/index.ts"
compatibility_date = "2025-11-25"
type = "javascript"

[[d1_databases]]
binding = "DB"
database_name = "casflo"
database_id = "fb305b83-a406-4454-a25c-c35c0482ca12"

[vars]
ACCESS_TOKEN_EXPIRES = "15m"
REFRESH_TOKEN_EXPIRES_DAYS = "30"
