name = "casflo-api"
main = "src/index.ts"
compatibility_date = "2025-11-25"

routes = [
  { pattern = "api.casflo.id/*", zone_name = "casflo.id", custom_domain = true }
]

[vars]
ACCESS_TOKEN_EXPIRES = "15m"
REFRESH_TOKEN_EXPIRES_DAYS = 30
JWT_SECRET = "set_in_dashboard"
JWT_REFRESH_SECRET = "set_in_dashboard"
PASSWORD_PEPPER = "set_in_dashboard"

# Optional AI keys: set via Dashboard
# OPENAI_API_KEY = ""
# GEMINI_API_KEY = ""

[[d1_databases]]
binding = "DB"
database_name = "casflo"
database_id = "fb305b83-a406-4454-a25c-c35c0482ca12"
